name: CI

on:
  push:
    branches: [ master ]



jobs:
  # This workflow contains a single job called "build" 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get all code
        uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build
        
      - name: Copy app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "test"
          

    
